### ISSUE TITLE
DB2 connection drop on idle traffic

### ISSUE THREAD

**Issue by naveen-venkat** [strongloop/loopback-connector-db2#42] opened 2016-08-12 15:33 UTC
We are using loopback V2.22.0 and loopback-connector-DB2 V1.0.17 and connecting to the DB2 mainframe with client certificate.

When the application is idle for a day, the connection between Node and DB2 gets dropped then we try to hit the API, connector is unable to re establish the connection and logs below error, then we manually restart the instance to establish the connection, 

2016-07-17 21:30:50 +01:00: { [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "172.20.176.66".  Communication function detecting the error: "send".  Protocol specific error code(s): "110", "*", "*".  SQLSTATE=08001
]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "172.20.176.66".  Communication function detecting the error: "send".  Protocol specific error code(s): "110", "*", "*".  SQLSTATE=08001\n',
  state: '40003' }
2016-07-17 21:30:58 +01:00: { message: 'Connection not open.' }
2016-07-17 21:31:17 +01:00: { message: 'Connection not open.' }
2016-07-17 21:31:45 +01:00: { message: 'Connection not open.' }
 
2016-07-11 05:45:13 +01:00: { [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "172.20.176.66".  Communication function detecting the error: "send".  Protocol specific error code(s): "32", "*", "0".  SQLSTATE=08001
]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "172.20.176.66".  Communication function detecting the error: "send".  Protocol specific error code(s): "32", "*", "0".  SQLSTATE=08001\n',
  state: '40003' }
2016-07-11 05:45:25 +01:00: { message: 'Connection not open.' }
2016-07-11 05:45:49 +01:00: { message: 'Connection not open.' }
2016-07-11 05:52:49 +01:00: { message: 'Connection not open.' }

**Comment by qpresley** [comment] 2016-08-23 13:10
@naveen-venkat This is most likely caused by the TCP/IP keep alive timeout for the OS.  Typically this is set to 2 hours and if there has been no traffic over the connection in that time the TCP/IP link is closed and thus the connection is lost.  If your app is idle for a long time it will lose the connection.

**Comment by naveen-venkat** [comment] 2016-08-23 17:54
@qpresley, yes you are correct. But after the connection drop, i believe the connector should be able to establish new connection? right now it does not establish new connection, nor throws an error so that the application will be killed, we had to restart the instance to establish the new connection.

I discussed this issue with Anthony (AWhalley@ie.ibm.com), he has confirmed that the application throws error in a case where the client certificate isn't used and since we are using client certificate the application isn't throwing the error.

**Comment by qpresley** [comment] 2016-08-29 14:23
@naveen-venkat It is debatable whether or not this is something that should be handled by the driver vs. the application.  When holding idle connections open vs. returning to the connection pool there is no layer in the stack that will be able to distinguish between this SQL30081N error or another that occurs for reasons other than TCP/IP timeout.

If for example infinite retry to establish a new connection was implemented on return of SQL30081N and the DBA did not configure DB2COMM and SVCENAME correctly in the DB2 configuration for LUW or DB2 Connect then the application would appear to hang as it continually attempts to connect to a database that is incorrectly configured.  From the client side perspective this looks identical to a TCP/IP timeout.

If instead the application closed the connection, which really just returns the connection to a connection pool then this issue doesn't exist as the connection pool logic handles ensuring the caller gets a properly open and accessible connection to the database.

**Comment by naveen-venkat** [comment] 2016-08-31 10:50
@qpresley, i'm trying the create a connection pooling but could not find any configuration option in the connector, could you please help me in configuring the pooling size?

**Comment by qpresley** [comment] 2016-08-31 11:25
@naveen-venkat It is using the pooling already. When you open a connection in the loopback-connector-db2 it uses a pooled connection. What you need to do though is close the connection when it is not in use. The close will return it to the pool vs. physically closing the connection so a subsequent connection request does not travel back to the database as an open one already exists.

There may be other database or system configurations that can be changed to affect the connection timeout such as TCP/IP tuning however I don't know much about that area.

The pooling is done in the node-ibm_db module which the connector depends on.  It is pretty primitive pooling and doesn't have configuration.

**Comment by naveen-venkat** [comment] 2016-08-31 12:25
@qpresley, since we are using this connector as a datasource and every thing is a configuration in the datasource, not sure if we have access to the database resources, could you please provide a hint to access the resource so that i can play around the connection pooling/ opening/closing connections?

**Comment by qpresley** [comment] 2016-08-31 12:50
@naveen-venkat here is a simple example app.

```
var DataSource = require('loopback-datasource-juggler').DataSource;
var DB2 = require('../'); // loopback-connector-db2

var config = {
  username: process.env.DB2_USERNAME,
  password: process.env.DB2_PASSWORD,
  hostname: process.env.DB2_HOSTNAME,
  port: process.env.DB2_PORTNUM,
  database: process.env.DB2_DATABASE,
  lazyConnect: true,
};

var db = new DataSource(DB2, config);

var conn = db.connector.connect(function(err, conn) {
  if (err) {
    console.log(err);
  } else {
    var good = db.connector.testConnection(conn,
                          'SELECT COUNT(*) AS COUNT FROM SYSIBM.SYSTABLES');
    if (good) {
      console.log('Successfully connected');
    }

    conn.close(function(err) {
      if(err) console.log(err);
    });
  }
});
```

**Comment by qpresley** [comment] 2016-08-31 12:53
Note the use of lazyConnect to indicate that you don't want a connection allocated at initialization.  This isn't required but can be useful.  The rest of the code just accesses methods off the DataSource object.  The alternative to what is above is to continue to use the testConnection function which takes a simple Query to validate the connection is still good.

**Comment by naveen-venkat** [comment] 2016-08-31 14:25
Thanks @qpresley, ill keep you updated on my findings.

**Comment by naveen-venkat** [comment] 2016-09-08 17:07
@qpresley, was able to find the fix for reconnecting the DB after connection drop, have raised a pull request, https://github.com/strongloop/loopback-ibmdb/pull/9 

Thanks to you and Anthony Whalley, helped alot to fix this issue.

**Comment by 0candy** [comment] 2016-09-12 21:58
PR merged, closing issue.

**Closed by 0candy** 2016-09-12 21:58 UTC
