### ISSUE TITLE
IBM i DB2 Compatibility

### ISSUE THREAD

**Issue by chadbean** [strongloop/loopback-connector-db2#33] opened 2016-05-09 13:54 UTC
Has there been any attempt or work done to make this compatible with DB2 on the IBM i Series? What work would be needed to make this possible? Happy to help if needed.

**Comment by qpresley** [comment] 2016-05-10 12:18
This is a duplicate of issue #30.  There has been no progress on DB2 iSeries support as I have not been able to get a system that I can point the connector at and see what changes would be needed.

**Comment by qpresley** [comment] 2016-08-23 13:05
Please see https://github.com/strongloop/loopback-connector-db2iseries

**Closed by qpresley** 2016-08-23 13:05 UTC
